# Generated by Django 3.1.4 on 2020-12-21 09:37

import app.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201220_0135'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app.managers.UserManager()),
            ],
        ),
    ]
