# Generated by Django 3.1.4 on 2020-12-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201222_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpagecontent',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='blogpagecontent',
            name='content',
            field=models.TextField(),
        ),
    ]
